site_name: JTD.Workspace
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
  # light mode
  - scheme: default
    primary: red
    toggle:
      icon: material/brightness-7
      name: Dark Mode
  # dark mode
  - scheme: slate
    primary: red
    toggle:
      icon: material/brightness-3
      name: Light Mode
  font:
    text: Oxanium
    code: Oxanium
